apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services-ingress
  namespace: services
spec:
  ingressClassName: nginx
  rules:
    - host: mango.neurocollab.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mango
                port:
                  number: 8080
    - host: uio-mcp.neurocollab.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uio-mcp-gateway
                port:
                  number: 3002
    - host: erp.neurocollab.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frappe-frontend
                port:
                  number: 8080